# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onoff.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='onoff.proto',
  package='onoff',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bonoff.proto\x12\x05onoff\"\x07\n\x05\x45mpty\"\x16\n\x05State\x12\r\n\x05onoff\x18\x01 \x01(\x08\" \n\rRequestStatus\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32k\n\x05onoff\x12\x30\n\x0eGetStateStream\x12\x0c.onoff.Empty\x1a\x0c.onoff.State\"\x00\x30\x01\x12\x30\n\x08SetState\x12\x0c.onoff.State\x1a\x14.onoff.RequestStatus\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='onoff.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_STATE = _descriptor.Descriptor(
  name='State',
  full_name='onoff.State',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='onoff', full_name='onoff.State.onoff', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=53,
)


_REQUESTSTATUS = _descriptor.Descriptor(
  name='RequestStatus',
  full_name='onoff.RequestStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='onoff.RequestStatus.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['State'] = _STATE
DESCRIPTOR.message_types_by_name['RequestStatus'] = _REQUESTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'onoff_pb2'
  # @@protoc_insertion_point(class_scope:onoff.Empty)
  })
_sym_db.RegisterMessage(Empty)

State = _reflection.GeneratedProtocolMessageType('State', (_message.Message,), {
  'DESCRIPTOR' : _STATE,
  '__module__' : 'onoff_pb2'
  # @@protoc_insertion_point(class_scope:onoff.State)
  })
_sym_db.RegisterMessage(State)

RequestStatus = _reflection.GeneratedProtocolMessageType('RequestStatus', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTSTATUS,
  '__module__' : 'onoff_pb2'
  # @@protoc_insertion_point(class_scope:onoff.RequestStatus)
  })
_sym_db.RegisterMessage(RequestStatus)



_ONOFF = _descriptor.ServiceDescriptor(
  name='onoff',
  full_name='onoff.onoff',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=89,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStateStream',
    full_name='onoff.onoff.GetStateStream',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_STATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetState',
    full_name='onoff.onoff.SetState',
    index=1,
    containing_service=None,
    input_type=_STATE,
    output_type=_REQUESTSTATUS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONOFF)

DESCRIPTOR.services_by_name['onoff'] = _ONOFF

# @@protoc_insertion_point(module_scope)
