# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import onoff_pb2 as onoff__pb2


class onoffStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStateStream = channel.unary_stream(
                '/onoff.onoff/GetStateStream',
                request_serializer=onoff__pb2.Empty.SerializeToString,
                response_deserializer=onoff__pb2.State.FromString,
                )
        self.SetState = channel.unary_unary(
                '/onoff.onoff/SetState',
                request_serializer=onoff__pb2.State.SerializeToString,
                response_deserializer=onoff__pb2.RequestStatus.FromString,
                )


class onoffServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetStateStream(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetState(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_onoffServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetStateStream,
                    request_deserializer=onoff__pb2.Empty.FromString,
                    response_serializer=onoff__pb2.State.SerializeToString,
            ),
            'SetState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetState,
                    request_deserializer=onoff__pb2.State.FromString,
                    response_serializer=onoff__pb2.RequestStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onoff.onoff', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class onoff(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetStateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/onoff.onoff/GetStateStream',
            onoff__pb2.Empty.SerializeToString,
            onoff__pb2.State.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onoff.onoff/SetState',
            onoff__pb2.State.SerializeToString,
            onoff__pb2.RequestStatus.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
